server:
  port: 8010
spring:
  application:
    name: microservice-simple-consumer-movie  
eureka:
  client:
    serviceUrl:
      #defaultZone: http://user:password123@localhost:8761/eureka/
      defaultZone: http://peer2:8762/eureka/
  instance:
    prefer-ip-address: true #表示将自己的IP注册到Eureka Server